CREATE TABLE IF NOT EXISTS otp (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    otp_code VARCHAR(6) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE EVENT IF NOT EXISTS delete_expired_otps
ON SCHEDULE EVERY 1 MINUTE
DO
  DELETE FROM otp WHERE TIMESTAMPDIFF(MINUTE, created_at, NOW()) >= 10;